## Enrichments

Current implementation:
- Counts based on Target-Disease-Trial triples
- Exclude some EVA evidence (beningns, unknown significance, etc.)

```{r, runFisherTests, cache = TRUE}
aggregations_path <- "gs://ot-team/dochoa/predictions_aggregations/*.parquet"
all_aggregations <- spark_read_parquet(sc, aggregations_path) %>%
    mutate(b = predictionTotal - a) %>%
    mutate(c = comparisonTotal - a) %>%
    mutate(d = total - b - c + a) %>%
    collect()


all_tests <- bind_cols(
    all_aggregations,
    all_aggregations %>%
        mutate(d = ifelse(d < 0, 0, d)) %>%
        rowwise() %>%
        do(broom::tidy(fisher.test(matrix(c(.$a, .$b, .$c, .$d), nrow = 2))))
)
    
```

### Stop reasons by datatype

```{r, metaStopByDatatype}

all_tests %>%
    filter(predictionType %in% c("metareason", "clinical", "stopStatus")) %>%
    filter(comparison %in% c("animal_model","genetic_association")) %>%
    filter(comparisonType == "byDatatype") %>%
    mutate(predictionType = fct_relevel(predictionType,
    "clinical", "stopStatus", "metareason")) %>%
    mutate(prediction = fct_reorder(prediction, estimate, median)) %>%
    mutate(comparison = fct_rev(comparison)) %>%
    ggplot(aes(x = prediction, y = estimate)) +
    geom_hline(aes(yintercept = 1),
        size = .25,
        linetype = "dashed"
    ) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
    width = 0) +
    geom_point() +
    scale_y_log10(name = "Odds Ratio (log)") +
    coord_flip() +
    facet_grid(
        predictionType ~ comparison,
        scales = "free_y",
        space = "free_y") +
    theme_cowplot() +
    panel_border(color = "black") +    
    theme(
        axis.title.y = element_blank(),
        # strip.text.y = element_blank(),
        strip.background = element_rect(fill = NA),
        panel.grid.major.y = element_blank()
    )
    
```

### Stop reasons (meta) by genetic datasource

```{r, metaStopByGeneticDatasource}
genetic_ds <- c(
    "clingen", 
    "eva",
    # "gene2phenotype",
    "genomics_england",
    "ot_genetics_portal",
    # "phewas_catalog",
    "uniprot_literature",
    "uniprot_variants"
)
all_tests %>%
    filter(predictionType %in% c("metareason", "clinical", "stopStatus")) %>%
    filter(comparison %in% genetic_ds) %>%
    filter(comparisonType == "byDatasource") %>%
    mutate(predictionType = fct_relevel(predictionType,
    "clinical", "stopStatus", "metareason")) %>%
    mutate(prediction = fct_reorder(prediction, estimate, median)) %>%
    # mutate(comparison = fct_rev(comparison)) %>%
    ggplot(aes(x = prediction, y = estimate)) +
    geom_hline(aes(yintercept = 1),
        size = .25,
        linetype = "dashed"
    ) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
    width = 0) +
    geom_point() +
    scale_y_log10(name = "Odds Ratio (log)") +
    coord_flip() +
    facet_grid(
        predictionType ~ comparison,
        scales = "free_y",
        space = "free_y") +
    theme_cowplot() +
    panel_border(color = "black") +    
    theme(
        axis.title.y = element_blank(),
        # strip.text.y = element_blank(),
        strip.background = element_rect(fill = NA),
        panel.grid.major.y = element_blank()
    )

```


### The Cancer - Safety enrichment signal

```{r, metaStopByCancerDatasource}
cancer_ds <- c("cancer_gene_census", "intogen", "eva_somatic")
all_tests %>%
    filter(predictionType %in% c("metareason", "clinical", "stopStatus")) %>%
    filter(comparison %in% cancer_ds) %>%
    filter(comparisonType == "byDatasource") %>%
    mutate(predictionType = fct_relevel(predictionType,
    "clinical", "stopStatus", "metareason")) %>%
    mutate(prediction = fct_reorder(prediction, estimate, median)) %>%
    # mutate(comparison = fct_rev(comparison)) %>%
    ggplot(aes(x = prediction, y = estimate)) +
    geom_hline(aes(yintercept = 1),
        size = .25,
        linetype = "dashed"
    ) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
    width = 0) +
    geom_point() +
    scale_y_log10(name = "Odds Ratio (log)") +
    coord_flip() +
    facet_grid(
        predictionType ~ comparison,
        scales = "free_y",
        space = "free_y") +
    theme_cowplot() +
    panel_border(color = "black") +    
    theme(
        axis.title.y = element_blank(),
        # strip.text.y = element_blank(),
        strip.background = element_rect(fill = NA),
        panel.grid.major.y = element_blank()
    )

```