---
title: "Study stop reasons"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    toc: true
---

# Clinical trial stop reason interpretation

```{r, knitSetup, include=FALSE}
knitr::opts_knit$set(root.dir = getwd())
knitr::opts_chunk$set(cache.path = "../temp/")
```

```{r, Rsetup, include = FALSE}
library("tidyverse")
library("sparklyr")
library("sparklyr.nested")
library("lubridate")
library("ggdendro")
library("ggsci")
library("cowplot")
```

```{r, SparkConnection, include = FALSE}
config <- spark_config()

# Allowing to GCP datasets access
config$spark.hadoop.fs.gs.requester.pays.mode <- "AUTO" # nolint
config$spark.hadoop.fs.gs.requester.pays.project.id <- "open-targets-eu-dev" # nolint

# spark connect
sc <- spark_connect(master = "yarn", config = config)
```

```{r, child = 'sections/sentenceSimilarities.rmd'}
```

```{r, child = 'sections/predictions.rmd'}
```

```{r, child = 'sections/efficacy.rmd'}
```

```{r, child = 'sections/safety.rmd'}
```

## TODO: Analysis by phase -> what happens with stopped T-Ds in subsequent phases
## TODO: come back to original paper